### ISSUE TITLE
pdfで出力してくれ

### ISSUE THREAD

**Issue by johta** [selab601/web_minutes#1]
pdfで出力に対応してほしいです

**Comment by tasuwo** [comment]
PDF 出力は，ブラウザの標準機能であるので，そちらを使用してください．

例えば，Firefox の場合，以下のように PDF 出力が選択できます．

![print](https://cloud.githubusercontent.com/assets/10893464/20645655/e5d6f28e-b4a7-11e6-957a-fbca2c8c1748.png)

**Comment by tasuwo** [comment]
ボタンを設置しました．HTML -> PDF 出力のための方法としては CakePdf 等のプラグインが考えられるのですが，CSSによってはかなり重いのと，出力結果が想定と大きく異なる場合が多いので，これ以上 PDF 出力対応を行う予定はありません．
